apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deployment
  labels:
    app: testapp-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp-2
  template:
    metadata:
      labels:
        app: testapp-2
    spec:
      containers:
      - name: testapp-2
        image: nginx  # Note the corrected image name
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - aks-agentpool-40053212-vmss000003
            topologyKey: "topology.kubernetes.io/region:eastus"
