apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: alpine:3.18.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
