apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
        requests:
          cpu: "10m"  # Minimum CPU request (10 milliCPU)
          memory: "20Mi"  # Minimum memory request (20 Mebibytes)
        limits:
          cpu: "100m"  # Maximum CPU limit (100 milliCPU)
          memory: "256Mi"  # Maximum memory limit (256 Mebibytes)